# Generated by Django 3.2.8 on 2021-12-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211202_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_contact',
        ),
    ]
